[2025-04-03T02:05:41.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T02:05:42.005+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T02:05:42.006+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-04-03T02:05:42.117+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data_parquet> on 2025-04-02 00:00:00+00:00
[2025-04-03T02:05:42.129+0000] {standard_task_runner.py:60} INFO - Started process 106 to run task
[2025-04-03T02:05:42.138+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'download_data_parquet', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmp7_zkccr5']
[2025-04-03T02:05:42.146+0000] {standard_task_runner.py:88} INFO - Job 87: Subtask download_data_parquet
[2025-04-03T02:05:42.295+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T02:05:42.458+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [running]> on host c604bbf95a3a
[2025-04-03T02:05:42.942+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='download_data_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-03T02:05:42.966+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 29, in download_data
    from pipeline.ingest.download_parquet import main as download_main
ModuleNotFoundError: No module named 'pipeline'
[2025-04-03T02:05:43.025+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=full_pipeline_dag, task_id=download_data_parquet, execution_date=20250402T000000, start_date=20250403T020541, end_date=20250403T020543
[2025-04-03T02:05:43.202+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 87 for task download_data_parquet (No module named 'pipeline'; 106)
[2025-04-03T02:05:43.243+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T02:05:43.323+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
