[2025-04-03T02:04:34.694+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T02:04:34.745+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T02:04:34.747+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-03T02:04:34.886+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data_parquet> on 2025-04-02 00:00:00+00:00
[2025-04-03T02:04:34.896+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2025-04-03T02:04:34.903+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'download_data_parquet', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpgg5noy1v']
[2025-04-03T02:04:34.909+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask download_data_parquet
[2025-04-03T02:04:35.037+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T02:04:35.189+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.download_data_parquet scheduled__2025-04-02T00:00:00+00:00 [running]> on host c604bbf95a3a
[2025-04-03T02:04:35.721+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='download_data_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-03T02:04:35.725+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 29, in download_data
    from .pipe import main as download_main
ImportError: attempted relative import with no known parent package
[2025-04-03T02:04:35.815+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=download_data_parquet, execution_date=20250402T000000, start_date=20250403T020434, end_date=20250403T020435
[2025-04-03T02:04:35.988+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task download_data_parquet (attempted relative import with no known parent package; 79)
[2025-04-03T02:04:36.008+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T02:04:36.117+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
