[2025-04-02T17:53:25.750+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T17:53:20.992532+00:00 [queued]>
[2025-04-02T17:53:25.768+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T17:53:20.992532+00:00 [queued]>
[2025-04-02T17:53:25.769+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-04-02T17:53:25.824+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data_parquet> on 2025-04-02 17:53:20.992532+00:00
[2025-04-02T17:53:25.827+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2025-04-02T17:53:25.829+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'download_data_parquet', 'manual__2025-04-02T17:53:20.992532+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpxeb935l9']
[2025-04-02T17:53:25.831+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask download_data_parquet
[2025-04-02T17:53:25.871+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-02T17:53:25.934+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T17:53:20.992532+00:00 [running]> on host 911906f4c794
[2025-04-02T17:53:26.102+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='download_data_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T17:53:20.992532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T17:53:20.992532+00:00'
[2025-04-02T17:53:26.103+0000] {logging_mixin.py:188} INFO - ðŸ›  PYTHONPATH in task: ['/home/airflow/.local/bin', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/home/airflow/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/site-packages', '/opt/airflow/dags', '/opt/airflow/config', '/opt/airflow/plugins']
[2025-04-02T17:53:26.107+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 35, in download_data
    from pipeline.ingest.download_parquet import main as download_main
ModuleNotFoundError: No module named 'pipeline'
[2025-04-02T17:53:26.123+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=download_data_parquet, execution_date=20250402T175320, start_date=20250402T175325, end_date=20250402T175326
[2025-04-02T17:53:26.161+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task download_data_parquet (No module named 'pipeline'; 233)
[2025-04-02T17:53:26.204+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-02T17:53:26.242+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
