[2025-04-03T04:21:38.943+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.upload_raw_to_minio manual__2025-04-03T04:21:10.456726+00:00 [queued]>
[2025-04-03T04:21:38.957+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.upload_raw_to_minio manual__2025-04-03T04:21:10.456726+00:00 [queued]>
[2025-04-03T04:21:38.957+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-04-03T04:21:38.990+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): upload_raw_to_minio> on 2025-04-03 04:21:10.456726+00:00
[2025-04-03T04:21:38.993+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2025-04-03T04:21:38.996+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'upload_raw_to_minio', 'manual__2025-04-03T04:21:10.456726+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmp2djuuuzi']
[2025-04-03T04:21:38.998+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask upload_raw_to_minio
[2025-04-03T04:21:39.037+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T04:21:39.100+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.upload_raw_to_minio manual__2025-04-03T04:21:10.456726+00:00 [running]> on host db23a8406c06
[2025-04-03T04:21:39.277+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='upload_raw_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T04:21:10.456726+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T04:21:10.456726+00:00'
[2025-04-03T04:21:39.318+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 37, in upload_data
    upload_tripdata_to_minio()
  File "/opt/pipeline/ingest/upload_to_minio.py", line 2, in upload_tripdata_to_minio
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-04-03T04:21:39.354+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=upload_raw_to_minio, execution_date=20250403T042110, start_date=20250403T042138, end_date=20250403T042139
[2025-04-03T04:21:39.418+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task upload_raw_to_minio (No module named 'minio'; 86)
[2025-04-03T04:21:39.451+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T04:21:39.503+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
