[2025-04-03T16:33:04.139+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T16:32:19.388432+00:00 [queued]>
[2025-04-03T16:33:04.154+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T16:32:19.388432+00:00 [queued]>
[2025-04-03T16:33:04.154+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-04-03T16:33:04.186+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): clean_data_spark> on 2025-04-03 16:32:19.388432+00:00
[2025-04-03T16:33:04.190+0000] {standard_task_runner.py:60} INFO - Started process 118 to run task
[2025-04-03T16:33:04.193+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'clean_data_spark', 'manual__2025-04-03T16:32:19.388432+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmprqri5csv']
[2025-04-03T16:33:04.196+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask clean_data_spark
[2025-04-03T16:33:04.243+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T16:33:04.304+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T16:32:19.388432+00:00 [running]> on host 06459006e56f
[2025-04-03T16:33:04.441+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='clean_data_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T16:32:19.388432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T16:32:19.388432+00:00'
[2025-04-03T16:33:04.458+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-03T16:33:04.459+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --queue root.default --deploy-mode client /opt/spark-app/clean_yellow_tripdata.py
[2025-04-03T16:33:04.509+0000] {spark_submit.py:649} INFO - /home/airflow/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-03T16:33:04.511+0000] {spark_submit.py:649} INFO - JAVA_HOME is not set
[2025-04-03T16:33:04.528+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 575, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --queue root.default --deploy-mode client /opt/spark-app/clean_yellow_tripdata.py. Error code is: 1.
[2025-04-03T16:33:04.531+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=clean_data_spark, execution_date=20250403T163219, start_date=20250403T163304, end_date=20250403T163304
[2025-04-03T16:33:04.675+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 171 for task clean_data_spark (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose --queue root.default --deploy-mode client /opt/spark-app/clean_yellow_tripdata.py. Error code is: 1.; 118)
[2025-04-03T16:33:04.688+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T16:33:04.716+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
