[2025-04-03T09:42:44.947+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T09:40:44+00:00 [queued]>
[2025-04-03T09:42:44.966+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T09:40:44+00:00 [queued]>
[2025-04-03T09:42:44.967+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-03T09:42:45.021+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): clean_data_spark> on 2025-04-03 09:40:44+00:00
[2025-04-03T09:42:45.026+0000] {standard_task_runner.py:60} INFO - Started process 134 to run task
[2025-04-03T09:42:45.030+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'clean_data_spark', 'manual__2025-04-03T09:40:44+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpqmdgbfc1']
[2025-04-03T09:42:45.032+0000] {standard_task_runner.py:88} INFO - Job 148: Subtask clean_data_spark
[2025-04-03T09:42:45.105+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T09:42:45.198+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.clean_data_spark manual__2025-04-03T09:40:44+00:00 [running]> on host ba1dea2bebed
[2025-04-03T09:42:45.413+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='clean_data_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T09:40:44+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T09:40:44+00:00'
[2025-04-03T09:42:45.415+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-03T09:42:45.416+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        docker run --rm         --network shared-net         -v /opt/airflow/spark-app:/opt/spark-app         -v /opt/data:/opt/data         bitnami/spark:3.5         /opt/spark/bin/spark-submit /opt/spark-app/clean_yellow_tripdata.py\n        ']
[2025-04-03T09:42:45.422+0000] {subprocess.py:86} INFO - Output:
[2025-04-03T09:42:45.582+0000] {subprocess.py:93} INFO - docker: Error response from daemon: network shared-net not found.
[2025-04-03T09:42:45.587+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2025-04-03T09:42:45.602+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-04-03T09:42:45.607+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=clean_data_spark, execution_date=20250403T094044, start_date=20250403T094244, end_date=20250403T094245
[2025-04-03T09:42:45.649+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 148 for task clean_data_spark (Bash command failed. The command returned a non-zero exit code 125.; 134)
[2025-04-03T09:42:45.688+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T09:42:45.726+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
